name: nf-core-circrna-1.0dev
channels:
  - agbiome
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bbtools=37.62
  - bioconductor-apeglm=1.8.0
  - bioconductor-biomart=2.42.0
  - bioconductor-deseq2=1.26.0
  - bioconductor-enhancedvolcano=1.4.0
  - bioconductor-ihw=1.14.0
  - bioconductor-org.hs.eg.db=3.10.0
  - bioconductor-pcatools=1.2.0
  - bioconductor-rhdf5=2.30.0
  - bioconductor-tximport=1.14.0
  - bowtie=1.2.3
  - bowtie2=2.3.5.1
  - bwa=0.7.17
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - circexplorer2=2.3.8
  - curl=7.68.0
  - hisat2=2.2.0
  - htslib=1.10.2
  - _libgcc_mutex=0.1
  - mapsplice=2.2.1
  - miranda=3.3a
  - _openmp_mutex=4.5
  - perl=5.26.2
  - picard=2.23.8
  - pip=20.0.2
  - python=2.7.15
  - conda-forge::r-argparser=0.6
  - conda-forge::r-circlize=0.4.11
  - conda-forge::r-dplyr=1.0.2
  - conda-forge::r-ggplot2=3.3.2
  - conda-forge::r-gplots=3.1.0
  - conda-forge::r-pheatmap=1.0.12
  - r-pvclust=2.2_0
  - r-rcolorbrewer=1.1_2
  - r-ggpubr=0.4.0
  - samtools=1.10
  - star=2.7.6a
  - stringtie=2.1.1
  - tophat=2.1.1
  - ucsc-genepredtobed=377
  - ucsc-genepredtogtf=377
  - ucsc-gtftogenepred=377
  - viennarna=2.4.15
  - wheel=0.34.2
  - zlib=1.2.11
  - pip:
    - argparse==1.2.1
    - ciriquant==1.1.1
    - numexpr==2.6.9
    - numpy==1.16.4
    - pysam==0.15.2
    - pyyaml==5.1.1
    - scikit-learn==0.20.3
    - scipy==1.2.2
